development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: solitaire_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: solitaire_test
  host: localhost
  pool: 5
