development:
  adapter: postgresql
  database: solitaire_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: solitaire_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: solitaire_prod
  pool: 5
  timeout: 5000
